Switch to `mamba` for dependency management, and document other required installation details
baker-laboratory/RoseTTAFold-All-Atom pull request #13
Opened 2024-03-10 20:04 UTC by amorehead

* Transitions the project to instead use `mamba` for dependency management, as `mamba` in my experience is oftentimes more platform-portable than Singularity/Apptainer.
* Documents other required installation details including `make_ss.sh` and `$PIPE_DIR` references.
* Fixes merging of MSAs following https://github.com/baker-laboratory/RoseTTAFold-All-Atom/pull/11.

2024-03-11 22:01 UTC, r-krishna requested changes
Thank you for creating the mamba dependencies for this project! I think users will really benefit from having this! 
Two minor points: 
1. I will upload the protein_sm example. My apologies for this. I would prefer to keep the current README example since that example was shown in the ms. 
2. I am not able to reproduce the bug that requires changing a3m["msa"][ to a3m[0], if you could send that to me I'm happy to debug!

2024-03-11 23:14 UTC, r-krishna commented on rf2aa/data/merge_inputs.py
> +            a3m_out[0],
Ok i was able to find the problem here and will fix it imminently. Please revert this commit and I will merge this PR in! Thank you so much for your contribution

2024-03-11 23:59 UTC, amorehead commented on README.md
> +Here is an example (from `rf2aa/config/inference/protein_complex_sm.yaml`):
No problem. I've reverted the README to only reference `protein_sm.yaml` in [this commit](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/pull/13/commits/ec93ac6346ad408105d1b7ef638245b35dd9602c).

2024-03-12 00:01 UTC, amorehead commented on rf2aa/data/merge_inputs.py
> +            a3m_out[0],
Sounds good. I've reverted this change in [this commit](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/pull/13/commits/1fcd8ec1a95a1e99ec16a560ef51a22f0b1a21a2).

2024-03-12 00:04 UTC, merged